apiVersion: v1
kind: Pod
metadata:
  name: shell-demo
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  - name: efs-pvc
    persistentVolumeClaim:
       claimName: efs
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
    - name: efs-pvc
      mountPath: "/efs"

